### ISSUE TITLE
[Feature Suggestion] Copy on enter

### ISSUE THREAD

**Issue by selrond** [radibit/alfred-coolors#1]
Would it be possible to have Copy to Clipboard as a default action on found color names?

**Comment by radibit** [comment]
Hey @selrond, thank you for the suggestion 🙂  I've just pushed a new version to address the `copy to clipboard` feature!

**Comment by selrond** [comment]
@radibit Will it prompt me to update automatically? Or do I have to manually install the newest version? If the latter is the case, then that's my second feature suggestion 😄

**Comment by radibit** [comment]
@selrond I just tested it and `alfred-notifier` is providing a message that there is a new update when the user requests the workflow in Alfred. However, it's still required to run `npm i -g alfred-coolors` so you can get the latest version :)

**Comment by selrond** [comment]
@radibit oh I totally forgot it's installed through npm :) nevermind then, thank you!

**Comment by selrond** [comment]
@radibit I've just installed the new version, but after I hit enter on chosen color name, system asks me which App do I want to use to open the URL 🤔

**Comment by radibit** [comment]
@selrond Please check if version 0.3.0 has been installed and restart Alfred in case the workflow is not referenced correctly.

**Comment by selrond** [comment]
@radibit nothing... Killed process, cleared Alfred's App Cache, checked version number... 🤔

**Comment by radibit** [comment]
@selrond that's really odd, sorry to hear it. Another suggestion I can give you is to remove the npm package `npm remove -g alfred-coolors`, delete the workflow in Alfred, and then installed it again `npm i -g alfred-coolors`. Hope that will fix it for you!
